<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>10.0</LangVersion>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <RepositoryUrl>https://github.com/mrchrisok/OandaV20.2</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <Authors>O. Chris Okonkwo</Authors>
        <Description>.NET library that enables integration with Oanda V20 Api</Description>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>

        <!-- Embed PDBs into DLL -->
        <DebugType>embedded</DebugType>

        <!-- SourceLink settings -->
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
        <!--<ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>-->

        <!-- Optional: Generate XML docs -->
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="OkonkwoCore.ServiceModel" Version="3.2026.904.93" />
    </ItemGroup>

</Project>
